### ISSUE TITLE
support different shape para

### ISSUE THREAD

**Issue by interestingzhuo** [ZhengyiLuo/UniversalHumanoidControl#7]
The beta is clipped via

```
body_params: 
    beta: 
      lb: -3
      ub: 3
```

Is it necessary? How to use the betas of SMPL to generate charater?  Could you give an example to generate charater via uhc/smpllib/smpl_robot.py and betas of SMPL/SMPLH?
